name: CI and CD
on:
  push:
    branches:
      - main
    paths:
      - src/**
      - build.sbt
      - .scalafix.conf
      - .scalafmt.conf
      - project/*
      - .github/**
  pull_request:
    paths:
      - src/**
      - build.sbt
      - .scalafix.conf
      - .scalafmt.conf
      - project/*
      - .github/**
jobs:
  ci-and-cd:
    uses: Lucky3028/shared-workflows/.github/workflows/scala-ci-and-cd.yml@af65de2
    with:
      cache-build-deps-ver: v-1
      cache-build-outputs-ver: v-1
      jar-output-dir: scala-2.13
